services:
  postgresql:
    image: postgres:13
    container_name: pgsql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app_api:
    image: my_image
    container_name: backend_container
    environment:  
      FAST_API_HOST: ${FAST_API_HOST}
      FAST_API_PORT: ${FAST_API_PORT}
      DBNAME: ${DBNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY} 
    ports:
      - ${FAST_API_PORT}:${FAST_API_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  telegram_bot:
    image: my_bot_image
    container_name: telegram_bot
    depends_on:
      - postgresql
      - app_api
    restart: unless-stopped

volumes:
  postgres_data: