FROM python:3.11-slim-bookworm
WORKDIR /app

COPY tg.py .

# Установи нужные зависимости, например aiogram, requests и т.д.
RUN pip install --no-cache-dir aiogram==3.15.0 aiohttp==3.9.3

CMD ["python", "tg.py"]